### ISSUE TITLE
just a white page with $queryTimer

### ISSUE THREAD

**Issue by KoljaL** [galanonym/phpsleekdbadmin#1]
dirty solution: `// $queryTimer ...`

**Comment by matkalis** [comment]
Not sure why this happen. White page usually shows when PHP error happens but display of errors are disabled. Was it a PHP error? Either way I have dropped QueryTimer class and used microtime() directly.

**Comment by KoljaL** [comment]
The PHP error is `Fatal error: Uncaught Error: Class "MicroTimer" not found in /www/htdocs/.../admin/phpsleekdbadmin.php:293`.
Moving the class before `start();` solves the problem :-)

**Comment by matkalis** [comment]
Thanks for feedback. I have removed the `MicroTimer` class, and moved `start();` to bottom of file, so it should work without hoisting too. Can you please check the newest version? :)
